# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/refs/tags/v2.10.1/schema/compose-spec.json
name: hello-world

services:
  server:
    build:
      context: .
    env_file:
      - .env
    environment:
      APP_MESSAGE: "Hello from compose!"
    ports:
      - name: http
        target: 8080
        published: "8080"
        protocol: tcp
        app_protocol: http
    volumes:
      - hello-data:/var/lib/hello
    configs:
      - source: app_config
        target: /app/config.yml
        mode: 0444
    secrets:
      - source: app_secret
        target: app-secret
    depends_on:
      db:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "/app/server.py", "--healthcheck"]

  db:
    image: docker.io/library/redis:7-alpine@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf
    expose:
      - "6379"
    volumes:
      - redis-data:/data

volumes:
  hello-data: {}
  redis-data: {}

configs:
  app_config:
    content: |
      server:
        greeting: "Hello from config map"

secrets:
  app_secret:
    file: ./app-secret.txt

x-uds:
  metadata:
    version: dev
  spec:
    network:
      expose:
        - service: server
    monitor:
      - service: server
        description: Server metrics
    # caBundle:
    #   configMap:
    #     name: uds-trust-bundle
    #     key: ca-bundle.pem
    #     labels:
    #       uds.dev/pod-reload: "true"
    # sso: []
